### ISSUE TITLE
Laboratory Work #0

### ISSUE THREAD

**Issue by defoltbl** [OS-IS/ai201-maksimenko#1]

**Comment by defoltbl** [comment]
![image](https://github.com/user-attachments/assets/dc7b0503-0c6b-43df-9ed1-f412df3e4c23)

**Comment by defoltbl** [comment]
![image](https://github.com/user-attachments/assets/333fa968-8a1d-4f29-8bce-285ae9282165)

**Comment by defoltbl** [comment]
![image](https://github.com/user-attachments/assets/7a47d65f-4896-4a4a-88b7-fe0923911ccc)

**Comment by AndreyMaksimenko** [comment]
![image](https://github.com/user-attachments/assets/d27ba184-bf59-454c-8be2-451c14ff54eb)

**Comment by defoltbl** [comment]
![image](https://github.com/user-attachments/assets/13892667-690f-4769-8a84-bc0cbe0b9431)

**Comment by AndreyMaksimenko** [comment]
![image](https://github.com/user-attachments/assets/ef593ede-9e64-4660-a067-76fda09bed9f)

**Comment by defoltbl** [comment]
![image](https://github.com/user-attachments/assets/3feee6a8-62ec-40db-875c-934de0f1a921)
