### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [OS-IS/ai201-maksimenko#4]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
4) Відомо, що з серпня 2021 року GitHub-сервер замінив класичний процес 
аутентифікації через пароль на процес з використанням Token 
під час безпечного оновлення GitHub-репозиторію. 
Поясніть, будь ласка, чому так було зроблено?

**Comment by defoltbl** [comment]
GitHub замінив класичну аутентифікацію через пароль на використання Personal Access Token (PAT) з серпня 2021 року для підвищення безпеки.
Основні причини цього рішення:
Паролі менш безпечні(Вони часто використовуються для доступу до різних сервісів і можуть бути схильні до атак типу "brute force" або фішингу.)
Токени мають більше контрольованих прав:(Personal Access Token (PAT) може бути обмежений за часом дії або функціональністю (наприклад, доступ лише до певних репозиторіїв або функцій), що зменшує потенційні ризики при компрометації, токени дозволяють більш гнучко управляти правами доступу, чого неможливо досягти зі звичайними паролями.)
Токени більш безпечні для зберігання(PAT не потрібно вводити вручну кожного разу, як пароль, тому його рідше піддають ризику витоку, як у випадку з багаторазовим використанням паролів у різних місцях.)
Захист від зловмисних дій(Токени можна швидко відкликати або замінити без необхідності змінювати весь пароль користувача, що спрощує процес відновлення безпеки в разі проблеми.)
Перехід на токени дозволяє підвищити загальний рівень безпеки GitHub-акаунтів і зменшити ризики зламів.

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 2 бали
Дякую.
